console.log("The quote 'there is no ecxercise better for the heart than reaching down and and lifting people up. ' by Jhon holmes teaches us to help another. ");
console.log("\"Love is not patronizing and charity isn't about pity, it is about love. Charity and love are the same -- with charity you give love, so don't just give money but reach out your hand instead.\"");
var variable = "Python";
// console.log(variable.includes("on"));
var frasedos = "Espero que este curso no esté lleno de jerga";
console.log(frasedos.indexOf("jerga") !== -1);
var number100 = Math.floor(Math.random() * 100);
console.log(number100);
var number50And100 = Math.floor(Math.random() * 101);
if (number50And100 >= 50)
    console.log(number50And100);
var aleatorio = Math.floor(Math.random() * 256);
console.log(aleatorio);
var cadena = "JavaScript";
var tam = cadena.length;
var indice = Math.floor(Math.random() * tam);
console.log(cadena[indice]);
var fraseDos = "No puedes terminar una oración con porque porque porque es una conjunción";
console.log(fraseDos);
var resultado = fraseDos.substring(35, 56);
console.log(resultado);
