var desafio = "30 dias de JavaScript";
console.log(desafio);
console.log(desafio.length);
console.log(desafio.toUpperCase());
console.log(desafio.toLowerCase());
console.log(desafio.substring(0, 3));
console.log(desafio.substring(3));
// console.log(desafio.includes("Script"));
console.log(desafio.split(""));
console.log(desafio.split(" "));
var companies = "Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon";
console.log(companies.split(","));
var newDesafio = desafio.replace("JavaScript", "Python");
console.log(newDesafio);
var indexFifteen = desafio.charAt(15);
console.log(indexFifteen);
var indexDeJ = desafio.charCodeAt(12);
console.log(indexDeJ);
console.log(desafio.indexOf("a"));
console.log(desafio.lastIndexOf("a"));
var frase = "No puedes terminar una oracion con porque porque porque en un conjuncion";
var primera = frase.indexOf("porque");
console.log(primera);
var ultima = frase.lastIndexOf("porque");
console.log(ultima);
var buscar = frase.search("porque");
console.log(buscar);
var desafio2 = "                              30 dias de JavaScript                          ";
console.log(desafio2);
console.log(desafio2.trim());
/* console.log(desafio.startsWith("30"));
console.log(desafio.endsWith("JavaScript")); */
var pattern = /a/gi;
console.log(desafio.match(pattern));
var oneFrase = "30 dias de ", twoFrase = "JAVASCRIPT";
console.log(oneFrase.concat(twoFrase));
// console.log(desafio.repeat(2));
